version: '3'
services:
    postgres:
        image: "postgres:9.6"
        networks:
            - kong-network
        restart: always
        container_name: "kong-ee-database"
        ports:
            - "5432"
        environment:
            POSTGRES_USER: "kong"
            POSTGRES_DB: "kong"
            POSTGRES_PASSWORD: "kong"
        volumes:
            - "./postgres:/var/lib/postgresql/data"
    kong-gateway:
        image: "kong/kong-gateway:2.6.0.0-alpine"
        depends_on:
            - postgres
        container_name: "kong-ee"
        networks:
            - kong-network
        restart: always
        ports:
            - "8000:8000"
            - "8443:8443"
            - "8001:8001"
            - "8444:8444"
            - "8002:8002"
            - "8445:8445"
            - "8003:8003"
            - "8004:8004"
        environment:
            KONG_DATABASE: "postgres"
            KONG_PG_HOST: "kong-ee-database"
            KONG_PG_PASSWORD: "kong"
            KONG_PASSWORD: "kong"
            KONG_PROXY_ACCESS_LOG: "/dev/stdout"
            KONG_ADMIN_ACCESS_LOG: "/dev/stdout"
            KONG_PROXY_ERROR_LOG: "/dev/stderr"
            KONG_ADMIN_ERROR_LOG: "/dev/stderr"
            KONG_ADMIN_LISTEN: "0.0.0.0:8001"
            KONG_ADMIN_GUI_URL: "http://0.0.0.0:8002"
        command: >
            bash -c "kong migrations bootstrap && kong start"
    konga-migrations:
        image: "pantsel/konga"
        depends_on:
            - postgres
        container_name: "konga-migrations"
        networks:
            - kong-network
        entrypoint: ""
        command: >
            bash -c "sleep 10 && /app/start.sh -c prepare -a postgres -u postgresql://kong:kong@kong-ee-database/konga"
    konga:
        image: "pantsel/konga"
        depends_on:
            - kong-gateway
            - konga-migrations
            - postgres
        container_name: "konga"
        networks:
            - kong-network
        restart: always
        ports:
            - "1337:1337"
        environment:
            NODE_ENV: "production"
            DB_ADAPTER: "postgres"
            DB_URI: "postgresql://kong:kong@kong-ee-database:5432/konga"
        volumes:
            - "./konga:/app/kongadata"
networks:
    kong-network: